### ISSUE TITLE
Datetime fields in parquet files cause errors

### ISSUE THREAD

**Issue by lbucas** [mukunku/ParquetViewer#1]
Hi,

i wanted to view a parquet file that contains a datetime field. However it caused this error:

![image](https://user-images.githubusercontent.com/32192444/43012845-34f906d6-8c15-11e8-8af4-89358fa29a07.png)

The file is not broken, as it worked within AWS Glue/Athena.

**Comment by mukunku** [comment]
Hi,

This seems to be an issue with the underlying Parquet.NET library. Can you post your issue along with a test file to the their repository: https://github.com/elastacloud/parquet-dotnet

Because it's currently out of my control unfortunately there isn't much I can help with. But just by looking at the exception it looks like the DateTime value in Col5 has a value that's maybe outside the range of .NET DateTime. I'm not sure how that can though because MSDN says the min for DateTime is: 00:00:00.0000000 UTC, January 1, 0001 and the max is: 23:59:59.9999999 UTC, December 31, 9999

Can you see what the problematic value is in another platform?

**Comment by mukunku** [comment]
Closing this issue as "Will not be fixed"
